### PR TITLE
Add component main color from user input

### PR DESCRIPTION
**Pull request by ghost**
--------
Pull Request Description
--------
##### What issue does this change request address?
#261 

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by PaulTalbot-INL** [comment]
This looks promising! Two questions:
1. Is there a test to cover this new feature?
2. Is the user _required_ to provide colors or do you pick one if they don't? I didn't immediately note that in the code, but I didn't look through it as closely as I should.

Thanks again for this PR.

**Comment by dylanjm** [comment]
> Is the user required to provide colors or do you pick one if they don't? I didn't immediately note that in the code, but I didn't look through it as closely as I should.

@PaulTalbot-INL I believe @yangx789 has it set up so that when we create the outer.xml we loop through the components and give them a default color value. If the user wants specific colors they can go into the outer.xml and modify them.

**Comment by ghost** [comment]
@PaulTalbot-INL @dylanjm 
1. I ran this feature with FORCE use cases 2021 and it works. Any other test we need to add for this feature?
2. It's an optional feature for users. Component colors will be added automatically in outer.xml from a pre-defined list. They can change color values if they want.

**Comment by PaulTalbot-INL** [comment]
@yangx789 Thanks! I will try to look at this ASAP; I'm pretty far behind on reviews right now. I do see there's a conflict in the DispatchPlot that needs resolving, though.

**Comment by PaulTalbot-INL** [comment]
We also need a regression test case that covers this modification. Adding color specification to one of the debug-related test cases should cover the testing, perhaps we can add a color request node to 
 https://github.com/idaholab/HERON/blob/devel/tests/integration_tests/mechanics/debug_mode/heron_input.xml?

**Comment by PaulTalbot-INL** [comment]
FYI, there's some issues with the testing machines with a recent library change; they're working on a fix now.

**Pull request closed without merging**
