### PR TITLE
Updates pickled ARMA ROMs

### LINKED ISSUE #194: [DEFECT] Changes to ARMA ROM in RAVEN has broken saved ROM pk files in tests
--------
Defect Description
--------

Recent changes to the ARMA ROM in RAVEN have broken existing pickled ROMs like those used in the HERON integration tests. These ROMs need to be retrained with the latest version of RAVEN.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by j-bryan**
--------
Pull Request Description
--------
##### What issue does this change request address?
#194 

##### What are the significant changes in functionality due to this change request?
No significant changes in functionality. Updates pickled ARMA ROMs and regolds one test (integration_tests/mechanics/labels/Labels) that had very slight differences in some values due to the recent RAVEN changes.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [x] 4. Automated Tests should pass.
- [x] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [x] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by dgarrett622** [comment]
@j-bryan for RAVEN compatibility issues like this one, in the future you can just link to issue #74 instead of creating a separate issue. It might save some time on your end 😄

**Comment by dgarrett622** [comment]
@PaulTalbot-INL HERON tests pass, but FARM tests do not. Looks like FARM has an ARMA that needs to be retrained to pass the heron_validator tests. Can this be merged anyway?

**Review by dgarrett622 — APPROVED** [review]

**Comment by PaulTalbot-INL** [comment]
It looks like FARM is using old ARMA files too ... I'm a little surprised they're using trained ARMAs that aren't in HERON. Let me look at their repo real quick and see if I can make sense of it.

**Comment by PaulTalbot-INL** [comment]
Yes, they're using ARMAs in their repo, which also need to be retrained. I will send Haoyu a note about this, but it shouldn't stop this PR ... although it looks like it does. Hm.

By our SQA, you only need to demonstrate that the plugin works with the current RAVEN and any plugins you depend on, which doesn't include FARM for HERON, so technically by the SQA this is okay to merge. We probably need to tinker with the test to be clearer on what plugins it uses, instead of "all".

**Comment by PaulTalbot-INL** [comment]
Okay. I talked with a couple people, and I think the right fix is to update the script that runs the tests to make sure we only check the plugins that we depend on, not "all". I'll come up with a fix and provide that to @j-bryan so you can include it in this PR, then we should be good to go.

However, we did fail to notify all plugin owners of the need to update ARMA, so we need to inform ANL specifically of that. I can send that email as well.

**Comment by PaulTalbot-INL** [comment]
Of course, because nothing is ever that simple, I have to get access to a private repo to make a change to a standard script that we use to install things as a RAVEN plugin. Since that's going to take a bit, I will note here that the tests we need to pass for this have passed, and approve an exception to the automated tests passing based on that. @dgarrett622 you can merge this if you feel the other requirements are satisfied.

**Comment by dgarrett622** [comment]
Okay, everything looks good for the HERON tests and no real code to review. I'll get this merged in. Thanks @j-bryan!

**Comment by j-bryan** [comment]
@PaulTalbot-INL I noticed the failing FARM test and submitted a PR to them to update that at the same time I made this one, so at the very least they should be aware of the issue.

**Comment by PaulTalbot-INL** [comment]
Perfect! Thank you.

**Pull request merged**
