### PR TITLE
Don't keep module functions, and add to python path.

### LINKED ISSUE #151: [TASK] Allow inner parallel to work with Raven Runs Raven
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
When running raven runs raven with internal parallel, the serialization of Placeholder doesn't work

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by joshua-cogliati-inl**
--------
Pull Request Description
--------
##### What issue does this change request address?
Closes #151 

##### What are the significant changes in functionality due to this change request?
* _module_methods in Function no longer keeps a link to the functions, which can be hard to serialize.
* If the target file is not in the path, it probably needs to be, so add it.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [x] 4. Automated Tests should pass.
- [x] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [x] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by joshua-cogliati-inl** [comment]
Changes also needed in RAVEN (or somewhere to add the correct paths to find HERON):
```diff
diff --git a/ravenframework/CustomDrivers/DriverUtils.py b/ravenframework/CustomDrivers/DriverUtils.py
index 176cba8..3e95b4b 100644
--- a/ravenframework/CustomDrivers/DriverUtils.py
+++ b/ravenframework/CustomDrivers/DriverUtils.py
@@ -108,6 +108,12 @@ def setupCpp():
     utils.add_path(os.path.join(frameworkDir,'contrib'))
     ##TODO REMOVE PP3 WHEN RAY IS AVAILABLE FOR WINDOWS
     utils.add_path_recursively(os.path.join(frameworkDir,'contrib','pp'))
+  #XXX Needed for HERON on cluster
+  ravenDir = os.path.dirname(frameworkDir)
+  heronSrc = os.path.join(ravenDir, "plugins", "HERON", "src")
+  if os.path.exists(heronSrc) and heronSrc not in sys.path:
+    sys.path.append(heronSrc)
+    sys.path.append(os.path.join(ravenDir, "scripts"))
 
 def checkVersions():
   """
```

**Comment by dylanjm** [comment]
@PaulTalbot-INL Was this something we wanted to merge? Will merging this require RAVEN to be changed with the patch @joshua-cogliati-inl provided?

**Comment by PaulTalbot-INL** [comment]
I don't think this requires RAVEN to be changed, but the changes Josh showed for RAVEN may be required to run HERON in parallel still.

I'm fine with merging this in, I'll do the review real quick.

**Review by PaulTalbot-INL — APPROVED** [review]
code changes are good

**Pull request merged**
