### PR TITLE
clean up the validators, now only with FARM_SISO and FARM_MIMO

### PR DESCRIPTION
**Pull request by wanghy-anl**
--------
Pull Request Description
--------
##### What issue does this change request address?
No related issues, but to clean up the validators list for FARM 2024 March 31 deliverable

##### What are the significant changes in functionality due to this change request?
1. Removed the prototype validators "FARM_Beta" and "FARM_Gamma_LTI"
2. Renamed the "FARM_Gamma_FMU" as "FARM_SISO"
3. Renamed the "FARM_Delta_FMU" as "FARM_MIMO"

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [x] 4. Automated Tests should pass.
- [x] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [x] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by wanghy-anl** [comment]
@PaulTalbot-INL @dylanjm Gents, I would like to clean up the FARM validator list from `HERON/src/validators/Factory.py`. 
Now there are only two validators left: 

- FARM_SISO (which is FARM_Gamma_FMU in the past) and 
- FARM_MIMO (which is FARM_Delta_FMU in the past). 

After this clean-up, a lot of repetition in the user manual could be cleared. The capabilities of FARM_Beta and FARM_Gamma_LTI has been merged into FARM_SISO.

Could you review and merge this PR?
Thanks,
Haoyu

**Review by dylanjm — APPROVED** [review]
Changes look good and all tests pass. Approved to merge.

**Comment by dylanjm** [comment]
@wanghy-anl This has been merged, please submit a submodule update to RAVEN if you need these features in the upcoming release of RAVEN.

**Comment by wanghy-anl** [comment]
@dylanjm Thank you Dylan. Do you have any plan on updating the HERON submodule in the next weeks? I would like to coordinate the development of FARM based on your schedule, so we can have FARM validator working together with HERON at the same time.

**Pull request merged**
