### PR TITLE
Pyomo mins

### LINKED ISSUE #18: ARMA for electric grid not able to access variables
--------

I have created a model that uses a steam generator that then uses a turbine to convert the steam to electricity. The electricity is then is consumed by two power grids. The primary grid that the electricity goes to has a load that is characterised by an ARMA model. For this model there are two ARMAs the first one is used for economic stuff as used in the production_flex test, and another one describes the demand for the power grid. This code runs great when I have the primary power grid at a fixed value but as soon as I change it to use an ARMA it breaks. I have been following the instruction manual that I built from the docs folder but it doesn't offer very much information for this part.

--------

It gave this error:
```
Traceback (most recent call last):
  File "/home/prism/repos/HERON/src/main.py", line 96, in <module>
    sim.read_input(args.xml_input_file) # TODO expand to use arguments?
  File "/home/prism/repos/HERON/src/main.py", line 52, in read_input
    objects = input_loader.parse(inp, location, self.messageHandler)
  File "/home/prism/repos/HERON/src/input_loader.py", line 58, in parse
    comp.read_input(comp_xml, case.get_mode())
  File "/home/prism/repos/HERON/src/Components.py", line 121, in read_input
    demand.read_input(item, mode, self.name)
  File "/home/prism/repos/HERON/src/Components.py", line 1085, in read_input
    Interaction.read_input(self, specs, mode, comp_name)
  File "/home/prism/repos/HERON/src/Components.py", line 412, in read_input
    self._set_valued_param(name, comp_name, item, mode)
  File "/home/prism/repos/HERON/src/Components.py", line 442, in _set_valued_param
    signal = vp.read(comp, spec, mode)
  File "/home/prism/repos/HERON/src/ValuedParams.py", line 152, in read
    typ, node, signal, request = self._load(comp_name, spec, mode, alias_dict)
  File "/home/prism/repos/HERON/src/ValuedParams.py", line 238, in _load
    signals = item.findFirst('ARMA').parameterValues['variable']
KeyError: 'variable'
```

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

[heron_input.txt](https://github.com/idaholab/HERON/files/5190242/heron_input.txt)
----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by PaulTalbot-INL**
--------
Pull Request Description
--------
##### What issue does this change request address?

Closes #18 
Contributes to #34 (however, EnsembleModel still crashes without at least one ARMA ROM)

##### What are the significant changes in functionality due to this change request?
- Modifies pyomo dispatcher to correctly grab minimum production levels from components
- Modifies pyomo dispatcher so that capacity and minimum production are assumed to be time-dependent values, allowing an ARMA to be used for either.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [x] 4. Automated Tests should pass.
- [x] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [x] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by PaulTalbot-INL** [comment]
It looks like Jason is working in CIVET right now, so the automated tests aren't running, but they passed on my local machine, so hopefully they'll pass automation once they're up.

**Review by dylanjm — COMMENTED** [review]
This looks great as well

**Review by dylanjm — COMMENTED** [review]
Looks great, no comments.

**Review by dylanjm — COMMENTED** [review]
Looks great no comments. Something weird must've happened. it's not registering my reviews. Hopefully last review.

**Review by dylanjm — APPROVED** [review]

**Pull request merged**
